server:
  port: 8081
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: INDfBdPAP/1cKmSBNT+P2wd3olAApJpKEXC0PudMI+0=
  expiration: 3600000